# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 225bc0abe1148b83fa19a8f9abdf87b5e168356286581d299cf10b9f80062070de868f0f7889584fb8aa825e3c931f28f5bc26637e511a78edd3707a003db3ba

test:
  secret_key_base: b20ac9191201aa8459b4655eb9aa286e6c2aec862dcff6f83dffeda2e66b107e66a7990e4a3d5aac2fa684ace239c81db640746cf43165064e450100bf7c1ab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
